name: ExoliaPlugin
version: 1.0
author: PLR_Power
main: fr.exolia.plugin.Main
commands:
  site:
    aliases: website
  vote:
  reglement:
  discord:
  hub:
    alisases: lobby
  hoteldevente:
  end:
  nether:
  mod:
  report:
